# Generated by Django 5.2.13 on 2026-05-08 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=500)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('emploi', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('cle', models.CharField(default='A', max_length=1)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('compteur', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='page1.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Conjoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjoints', to='page1.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_parent', models.CharField(choices=[('P', 'Père'), ('M', 'Mère')], max_length=1)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='page1.membre')),
            ],
        ),
    ]
