# Generated by Django 6.1.1 on 2026-10-05 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('A_PRODUIRE', 'À produire'), ('PRODUITE', 'Produite'), ('REMIS', 'Remise')], default='A_PRODUIRE', max_length=20)),
                ('date_production', models.DateTimeField(blank=True, null=True)),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carte', to='page1.membre')),
            ],
        ),
    ]
